version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_HOST: 
      DATABASE_PORT: 5432
      DATABASE_USER: 
      DATABASE_PASSWORD: 
      DATABASE_NAME: 
      REDIS_URL: redis://redis:6379/0
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    container_name: celery_worker
    command: celery -A main.celery worker --loglevel=info
    depends_on:
      - db
      - redis
    environment:
      DATABASE_HOST: 
      DATABASE_PORT: 
      DATABASE_USER: 
      DATABASE_PASSWORD: 
      DATABASE_NAME: 
      REDIS_URL: 
    volumes:
      - .:/app

volumes:
  postgres_data:
  redis_data:
